// ReactFrontend/src/claims/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from './auth';
import { Box, Button, Paper, TextField, Toolbar, Typography, CircularProgress, Divider, Snackbar, Alert } from '@mui/material';
import LoginIcon from '@mui/icons-material/Login';

const Login: React.FC = () => {
  const { login } = useAuth();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);
    const ok = await login(username, password);
    setSubmitting(false);
    if (ok) {
      setSuccess(true);
      setTimeout(() => navigate('/claims'), 1000);
    } else {
      setError('Invalid username or password.');
    }
  };

  return (
    <Box maxWidth={400} mx="auto" mt={8}>
      <Paper sx={{ p: 4 }} elevation={4}>
        <Toolbar sx={{ justifyContent: 'center', mb: 2 }}>
          <Typography variant="h5" fontWeight={600}>Sign In</Typography>
        </Toolbar>
        <Divider sx={{ mb: 2 }} />
        <form onSubmit={handleSubmit} noValidate autoComplete="off">
          <TextField
            label="Username"
            name="username"
            value={username}
            onChange={e => setUsername(e.target.value)}
            fullWidth
            margin="normal"
            required
            inputProps={{ 'aria-label': 'Username' }}
            autoFocus
          />
          <TextField
            label="Password"
            name="password"
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            fullWidth
            margin="normal"
            required
            inputProps={{ 'aria-label': 'Password' }}
          />
          {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
          <Box display="flex" justifyContent="flex-end" gap={2} mt={3}>
            <Button
              variant="contained"
              color="primary"
              type="submit"
              disabled={submitting}
              startIcon={<LoginIcon />}
              size="large"
              sx={{ minWidth: 120 }}
            >
              {submitting ? <CircularProgress size={24} color="inherit" /> : 'Login'}
            </Button>
          </Box>
        </form>
        <Snackbar open={success} autoHideDuration={1000} onClose={() => setSuccess(false)} anchorOrigin={{ vertical: 'top', horizontal: 'center' }}>
          <Alert severity="success" sx={{ width: '100%' }}>
            Login successful!
          </Alert>
        </Snackbar>
      </Paper>
    </Box>
  );
};

export default Login;

// AngularFrontend/src/app/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from './auth.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  loginForm: FormGroup;
  error: string | null = null;
  submitting = false;

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  onSubmit() {
    this.error = null;
    if (this.loginForm.invalid) return;
    this.submitting = true;
    const { username, password } = this.loginForm.value;
    this.auth.login(username, password).subscribe({
      next: (success) => {
        this.submitting = false;
        if (success) {
          this.router.navigate(['/claims']);
        } else {
          this.error = 'Invalid username or password.';
        }
      },
      error: () => {
        this.submitting = false;
        this.error = 'Invalid username or password.';
      }
    });
  }
}

<div class="login-container" style="display: flex; justify-content: center; align-items: center; min-height: 80vh;">
  <mat-card style="min-width: 350px; padding: 32px 24px;">
    <mat-card-title style="text-align: center; font-size: 1.5rem; font-weight: 600;">Sign In</mat-card-title>
    <mat-divider style="margin-bottom: 16px;"></mat-divider>
    <mat-card-content>
      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" autocomplete="off">
        <mat-form-field appearance="fill" style="width: 100%;">
          <mat-label>Username</mat-label>
          <input matInput formControlName="username" required aria-label="Username" autofocus />
        </mat-form-field>
        <mat-form-field appearance="fill" style="width: 100%;">
          <mat-label>Password</mat-label>
          <input matInput type="password" formControlName="password" required aria-label="Password" />
        </mat-form-field>
        <div *ngIf="error" class="error" style="margin-top: 12px;">
          <mat-error>{{ error }}</mat-error>
        </div>
        <div class="actions" style="display: flex; justify-content: flex-end; margin-top: 24px;">
          <button mat-raised-button color="primary" type="submit" [disabled]="submitting">
            <mat-icon>login</mat-icon>
            <span *ngIf="!submitting">Login</span>
            <mat-progress-spinner *ngIf="submitting" diameter="20" mode="indeterminate"></mat-progress-spinner>
          </button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
